// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package serverpb is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	SelectGroupRequest
	SelectGroupResponse
	SelectProfileRequest
	SelectProfileResponse
	GroupPutRequest
	GroupPutResponse
	GroupGetRequest
	GroupListRequest
	GroupGetResponse
	GroupListResponse
	ProfilePutRequest
	ProfilePutResponse
	ProfileGetRequest
	ProfileGetResponse
	ProfileListRequest
	ProfileListResponse
	IgnitionPutRequest
	IgnitionPutResponse
*/
package serverpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import storagepb "github.com/coreos/coreos-baremetal/bootcfg/storage/storagepb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SelectGroupRequest struct {
	Labels map[string]string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SelectGroupRequest) Reset()                    { *m = SelectGroupRequest{} }
func (m *SelectGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*SelectGroupRequest) ProtoMessage()               {}
func (*SelectGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SelectGroupRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type SelectGroupResponse struct {
	Group *storagepb.Group `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
}

func (m *SelectGroupResponse) Reset()                    { *m = SelectGroupResponse{} }
func (m *SelectGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*SelectGroupResponse) ProtoMessage()               {}
func (*SelectGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SelectGroupResponse) GetGroup() *storagepb.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type SelectProfileRequest struct {
	Labels map[string]string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SelectProfileRequest) Reset()                    { *m = SelectProfileRequest{} }
func (m *SelectProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*SelectProfileRequest) ProtoMessage()               {}
func (*SelectProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SelectProfileRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type SelectProfileResponse struct {
	Profile *storagepb.Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *SelectProfileResponse) Reset()                    { *m = SelectProfileResponse{} }
func (m *SelectProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*SelectProfileResponse) ProtoMessage()               {}
func (*SelectProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SelectProfileResponse) GetProfile() *storagepb.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type GroupPutRequest struct {
	Group *storagepb.Group `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
}

func (m *GroupPutRequest) Reset()                    { *m = GroupPutRequest{} }
func (m *GroupPutRequest) String() string            { return proto.CompactTextString(m) }
func (*GroupPutRequest) ProtoMessage()               {}
func (*GroupPutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GroupPutRequest) GetGroup() *storagepb.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupPutResponse struct {
}

func (m *GroupPutResponse) Reset()                    { *m = GroupPutResponse{} }
func (m *GroupPutResponse) String() string            { return proto.CompactTextString(m) }
func (*GroupPutResponse) ProtoMessage()               {}
func (*GroupPutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GroupGetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GroupGetRequest) Reset()                    { *m = GroupGetRequest{} }
func (m *GroupGetRequest) String() string            { return proto.CompactTextString(m) }
func (*GroupGetRequest) ProtoMessage()               {}
func (*GroupGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type GroupListRequest struct {
}

func (m *GroupListRequest) Reset()                    { *m = GroupListRequest{} }
func (m *GroupListRequest) String() string            { return proto.CompactTextString(m) }
func (*GroupListRequest) ProtoMessage()               {}
func (*GroupListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GroupGetResponse struct {
	Group *storagepb.Group `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
}

func (m *GroupGetResponse) Reset()                    { *m = GroupGetResponse{} }
func (m *GroupGetResponse) String() string            { return proto.CompactTextString(m) }
func (*GroupGetResponse) ProtoMessage()               {}
func (*GroupGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GroupGetResponse) GetGroup() *storagepb.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupListResponse struct {
	Groups []*storagepb.Group `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
}

func (m *GroupListResponse) Reset()                    { *m = GroupListResponse{} }
func (m *GroupListResponse) String() string            { return proto.CompactTextString(m) }
func (*GroupListResponse) ProtoMessage()               {}
func (*GroupListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GroupListResponse) GetGroups() []*storagepb.Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type ProfilePutRequest struct {
	Profile *storagepb.Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *ProfilePutRequest) Reset()                    { *m = ProfilePutRequest{} }
func (m *ProfilePutRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfilePutRequest) ProtoMessage()               {}
func (*ProfilePutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ProfilePutRequest) GetProfile() *storagepb.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type ProfilePutResponse struct {
}

func (m *ProfilePutResponse) Reset()                    { *m = ProfilePutResponse{} }
func (m *ProfilePutResponse) String() string            { return proto.CompactTextString(m) }
func (*ProfilePutResponse) ProtoMessage()               {}
func (*ProfilePutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ProfileGetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ProfileGetRequest) Reset()                    { *m = ProfileGetRequest{} }
func (m *ProfileGetRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfileGetRequest) ProtoMessage()               {}
func (*ProfileGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type ProfileGetResponse struct {
	Profile *storagepb.Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *ProfileGetResponse) Reset()                    { *m = ProfileGetResponse{} }
func (m *ProfileGetResponse) String() string            { return proto.CompactTextString(m) }
func (*ProfileGetResponse) ProtoMessage()               {}
func (*ProfileGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ProfileGetResponse) GetProfile() *storagepb.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type ProfileListRequest struct {
}

func (m *ProfileListRequest) Reset()                    { *m = ProfileListRequest{} }
func (m *ProfileListRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfileListRequest) ProtoMessage()               {}
func (*ProfileListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type ProfileListResponse struct {
	Profiles []*storagepb.Profile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
}

func (m *ProfileListResponse) Reset()                    { *m = ProfileListResponse{} }
func (m *ProfileListResponse) String() string            { return proto.CompactTextString(m) }
func (*ProfileListResponse) ProtoMessage()               {}
func (*ProfileListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ProfileListResponse) GetProfiles() []*storagepb.Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type IgnitionPutRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Config []byte `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *IgnitionPutRequest) Reset()                    { *m = IgnitionPutRequest{} }
func (m *IgnitionPutRequest) String() string            { return proto.CompactTextString(m) }
func (*IgnitionPutRequest) ProtoMessage()               {}
func (*IgnitionPutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type IgnitionPutResponse struct {
}

func (m *IgnitionPutResponse) Reset()                    { *m = IgnitionPutResponse{} }
func (m *IgnitionPutResponse) String() string            { return proto.CompactTextString(m) }
func (*IgnitionPutResponse) ProtoMessage()               {}
func (*IgnitionPutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func init() {
	proto.RegisterType((*SelectGroupRequest)(nil), "serverpb.SelectGroupRequest")
	proto.RegisterType((*SelectGroupResponse)(nil), "serverpb.SelectGroupResponse")
	proto.RegisterType((*SelectProfileRequest)(nil), "serverpb.SelectProfileRequest")
	proto.RegisterType((*SelectProfileResponse)(nil), "serverpb.SelectProfileResponse")
	proto.RegisterType((*GroupPutRequest)(nil), "serverpb.GroupPutRequest")
	proto.RegisterType((*GroupPutResponse)(nil), "serverpb.GroupPutResponse")
	proto.RegisterType((*GroupGetRequest)(nil), "serverpb.GroupGetRequest")
	proto.RegisterType((*GroupListRequest)(nil), "serverpb.GroupListRequest")
	proto.RegisterType((*GroupGetResponse)(nil), "serverpb.GroupGetResponse")
	proto.RegisterType((*GroupListResponse)(nil), "serverpb.GroupListResponse")
	proto.RegisterType((*ProfilePutRequest)(nil), "serverpb.ProfilePutRequest")
	proto.RegisterType((*ProfilePutResponse)(nil), "serverpb.ProfilePutResponse")
	proto.RegisterType((*ProfileGetRequest)(nil), "serverpb.ProfileGetRequest")
	proto.RegisterType((*ProfileGetResponse)(nil), "serverpb.ProfileGetResponse")
	proto.RegisterType((*ProfileListRequest)(nil), "serverpb.ProfileListRequest")
	proto.RegisterType((*ProfileListResponse)(nil), "serverpb.ProfileListResponse")
	proto.RegisterType((*IgnitionPutRequest)(nil), "serverpb.IgnitionPutRequest")
	proto.RegisterType((*IgnitionPutResponse)(nil), "serverpb.IgnitionPutResponse")
}

var fileDescriptor0 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x25, 0x5d, 0x37, 0xae, 0xb7, 0xb2, 0x76, 0xa7, 0x5d, 0x59, 0xf6, 0x49, 0x47, 0x90, 0x20,
	0x3a, 0x85, 0xf5, 0xc5, 0x5d, 0x58, 0x58, 0x17, 0xca, 0xa2, 0xec, 0x43, 0x89, 0xbf, 0x20, 0x89,
	0xb7, 0x31, 0x98, 0x64, 0xe2, 0xcc, 0xa4, 0xd0, 0x9f, 0xe1, 0x83, 0xff, 0xd7, 0x76, 0x3e, 0xe2,
	0xa4, 0x15, 0xb1, 0xe2, 0xd3, 0xdc, 0xb9, 0xf7, 0x9c, 0x73, 0x7b, 0xce, 0x94, 0xc0, 0x71, 0x85,
	0x52, 0x26, 0x39, 0x4a, 0xd6, 0x08, 0xae, 0x38, 0x39, 0x92, 0x28, 0x96, 0x28, 0x9a, 0xf4, 0xfc,
	0x63, 0x5e, 0xa8, 0x2f, 0x6d, 0xca, 0x32, 0x5e, 0x4d, 0x33, 0x2e, 0x90, 0x4b, 0x7b, 0xbc, 0x49,
	0x13, 0x81, 0x15, 0xaa, 0xa4, 0x9c, 0xa6, 0x9c, 0xab, 0x6c, 0x91, 0x4f, 0xa5, 0xe2, 0x62, 0x2d,
	0xe2, 0xce, 0x26, 0x75, 0x95, 0x51, 0xa5, 0xdf, 0x03, 0x20, 0x9f, 0xb0, 0xc4, 0x4c, 0xdd, 0x09,
	0xde, 0x36, 0x31, 0x7e, 0x6b, 0x51, 0x2a, 0x72, 0x03, 0x61, 0x99, 0xa4, 0x58, 0xca, 0xb3, 0xe0,
	0xd9, 0x41, 0x34, 0xbc, 0x88, 0x98, 0xdb, 0xce, 0x76, 0xd1, 0xec, 0x5e, 0x43, 0x67, 0xb5, 0x12,
	0xab, 0xd8, 0xf2, 0xce, 0x2f, 0x61, 0xe8, 0xb5, 0xc9, 0x08, 0x0e, 0xbe, 0xe2, 0x6a, 0xad, 0x16,
	0x44, 0x8f, 0xe2, 0x4d, 0x49, 0x26, 0x70, 0xb8, 0x4c, 0xca, 0x16, 0xcf, 0x06, 0xba, 0x67, 0x2e,
	0x57, 0x83, 0x77, 0x01, 0xbd, 0x86, 0x71, 0x6f, 0x89, 0x6c, 0x78, 0x2d, 0x91, 0xbc, 0x84, 0xc3,
	0x7c, 0xd3, 0xd0, 0x22, 0xc3, 0x8b, 0x11, 0xeb, 0x3c, 0x31, 0x03, 0x34, 0x63, 0xfa, 0x23, 0x80,
	0x89, 0xe1, 0xcf, 0x05, 0x5f, 0x14, 0x25, 0x3a, 0x53, 0xb7, 0x5b, 0xa6, 0x5e, 0x6d, 0x9b, 0xea,
	0xe3, 0xff, 0xb7, 0xad, 0x19, 0x9c, 0x6e, 0xad, 0xb1, 0xc6, 0x5e, 0xc3, 0xc3, 0xc6, 0xb4, 0xac,
	0x35, 0xe2, 0x59, 0x73, 0x60, 0x07, 0xa1, 0x97, 0xf0, 0x44, 0xdb, 0x9d, 0xb7, 0xca, 0x19, 0xfb,
	0xdb, 0x64, 0x08, 0x8c, 0x7e, 0x51, 0xcd, 0x72, 0xfa, 0xdc, 0xca, 0xdd, 0x61, 0x27, 0x77, 0x0c,
	0x83, 0xe2, 0xb3, 0xf5, 0xb4, 0xae, 0x3a, 0xda, 0x7d, 0x21, 0x1d, 0x86, 0x5e, 0xd9, 0x9e, 0xa6,
	0xed, 0xf9, 0x40, 0xd7, 0x70, 0xe2, 0xe9, 0x59, 0x72, 0x04, 0xa1, 0x9e, 0xba, 0xc7, 0xd9, 0x65,
	0xdb, 0x39, 0x7d, 0x0f, 0x27, 0x36, 0x14, 0x2f, 0x82, 0xfd, 0x32, 0x9c, 0x00, 0xf1, 0x25, 0x6c,
	0x14, 0x2f, 0x3a, 0xe1, 0x3f, 0x84, 0x71, 0xdb, 0x51, 0x7d, 0xeb, 0xff, 0xba, 0xde, 0x8f, 0x74,
	0x06, 0xe3, 0x5e, 0xd7, 0x4a, 0x33, 0x38, 0xb2, 0x3c, 0x17, 0xcd, 0xef, 0xb4, 0x3b, 0x0c, 0xbd,
	0x01, 0xf2, 0x21, 0xaf, 0x0b, 0x55, 0xf0, 0xda, 0xcb, 0x87, 0xc0, 0x83, 0x3a, 0xa9, 0xd0, 0x1a,
	0xd1, 0x35, 0x79, 0x0a, 0x61, 0xc6, 0xeb, 0x45, 0x91, 0xeb, 0xff, 0xea, 0xe3, 0xd8, 0xde, 0xe8,
	0x29, 0x8c, 0x7b, 0x0a, 0xe6, 0x87, 0xa4, 0xa1, 0xfe, 0x62, 0xbc, 0xfd, 0x19, 0x00, 0x00, 0xff,
	0xff, 0x19, 0xef, 0xe3, 0x5b, 0x99, 0x04, 0x00, 0x00,
}
