// Code generated by protoc-gen-go.
// source: storage.proto
// DO NOT EDIT!

/*
Package storagepb is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	Group
	Profile
	NetBoot
*/
package storagepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Group selects one or more machines and matches them to a Profile.
type Group struct {
	// machine readable Id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// human readable name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Profile id
	Profile string `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
	// Selectors to match machines
	Selector map[string]string `protobuf:"bytes,4,rep,name=selector" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// JSON encoded metadata
	Metadata []byte `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *Group) GetSelector() map[string]string {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *Group) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Profile defines the boot and provisioning behavior of a group of machines.
type Profile struct {
	// profile id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// human readable name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// ignition id
	IgnitionId string `protobuf:"bytes,3,opt,name=ignition_id,json=ignitionId" json:"ignition_id,omitempty"`
	// cloud config id
	CloudId string `protobuf:"bytes,4,opt,name=cloud_id,json=cloudId" json:"cloud_id,omitempty"`
	// support network boot / PXE
	Boot *NetBoot `protobuf:"bytes,5,opt,name=boot" json:"boot,omitempty"`
	// generic config id
	GenericId string `protobuf:"bytes,6,opt,name=generic_id,json=genericId" json:"generic_id,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetIgnitionId() string {
	if m != nil {
		return m.IgnitionId
	}
	return ""
}

func (m *Profile) GetCloudId() string {
	if m != nil {
		return m.CloudId
	}
	return ""
}

func (m *Profile) GetBoot() *NetBoot {
	if m != nil {
		return m.Boot
	}
	return nil
}

func (m *Profile) GetGenericId() string {
	if m != nil {
		return m.GenericId
	}
	return ""
}

// NetBoot describes network or PXE boot settings for a machine.
type NetBoot struct {
	// the URL of the kernel image
	Kernel string `protobuf:"bytes,1,opt,name=kernel" json:"kernel,omitempty"`
	// the init RAM filesystem URLs
	Initrd []string `protobuf:"bytes,2,rep,name=initrd" json:"initrd,omitempty"`
	// kernel args
	Args []string `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
}

func (m *NetBoot) Reset()                    { *m = NetBoot{} }
func (m *NetBoot) String() string            { return proto.CompactTextString(m) }
func (*NetBoot) ProtoMessage()               {}
func (*NetBoot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NetBoot) GetKernel() string {
	if m != nil {
		return m.Kernel
	}
	return ""
}

func (m *NetBoot) GetInitrd() []string {
	if m != nil {
		return m.Initrd
	}
	return nil
}

func (m *NetBoot) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Group)(nil), "storagepb.Group")
	proto.RegisterType((*Profile)(nil), "storagepb.Profile")
	proto.RegisterType((*NetBoot)(nil), "storagepb.NetBoot")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xc9, 0x9f, 0x36, 0xc9, 0xf4, 0xed, 0x4b, 0x19, 0x44, 0xd6, 0x82, 0x1a, 0x7a, 0x90,
	0x9e, 0x72, 0xa8, 0x17, 0xa9, 0x37, 0x41, 0xa4, 0x1e, 0x44, 0xe2, 0x55, 0x90, 0x6d, 0x76, 0x0c,
	0x4b, 0xd3, 0xdd, 0xb0, 0xdd, 0x0a, 0xfd, 0x56, 0x7e, 0x1e, 0x3f, 0x8d, 0x64, 0xbb, 0x2d, 0x7a,
	0xf3, 0x36, 0xbf, 0x67, 0x27, 0x33, 0xcf, 0x33, 0x81, 0xe1, 0xc6, 0x6a, 0xc3, 0x6b, 0x2a, 0x5a,
	0xa3, 0xad, 0xc6, 0xcc, 0x63, 0xbb, 0x9c, 0x7c, 0x05, 0xd0, 0x7b, 0x30, 0x7a, 0xdb, 0xe2, 0x7f,
	0x08, 0xa5, 0x60, 0x41, 0x1e, 0x4c, 0xb3, 0x32, 0x94, 0x02, 0x11, 0x62, 0xc5, 0xd7, 0xc4, 0x42,
	0xa7, 0xb8, 0x1a, 0x19, 0x24, 0xad, 0xd1, 0xef, 0xb2, 0x21, 0x16, 0x39, 0xf9, 0x80, 0x38, 0x87,
	0x74, 0x43, 0x0d, 0x55, 0x56, 0x1b, 0x16, 0xe7, 0xd1, 0x74, 0x30, 0xbb, 0x28, 0x8e, 0x5b, 0x0a,
	0xb7, 0xa1, 0x78, 0xf1, 0x0d, 0xf7, 0xca, 0x9a, 0x5d, 0x79, 0xec, 0xc7, 0x31, 0xa4, 0x6b, 0xb2,
	0x5c, 0x70, 0xcb, 0x59, 0x2f, 0x0f, 0xa6, 0xff, 0xca, 0x23, 0x8f, 0x6f, 0x61, 0xf8, 0xeb, 0x33,
	0x1c, 0x41, 0xb4, 0xa2, 0x9d, 0xf7, 0xd9, 0x95, 0x78, 0x02, 0xbd, 0x0f, 0xde, 0x6c, 0x0f, 0x4e,
	0xf7, 0x30, 0x0f, 0x6f, 0x82, 0xc9, 0x67, 0x00, 0xc9, 0xb3, 0x37, 0xf8, 0x97, 0x78, 0x97, 0x30,
	0x90, 0xb5, 0x92, 0x56, 0x6a, 0xf5, 0x26, 0x85, 0x8f, 0x08, 0x07, 0x69, 0x21, 0xf0, 0x0c, 0xd2,
	0xaa, 0xd1, 0x5b, 0xd1, 0xbd, 0xc6, 0xfb, 0x03, 0x38, 0x5e, 0x08, 0xbc, 0x82, 0x78, 0xa9, 0xb5,
	0x75, 0x01, 0x06, 0x33, 0xfc, 0x11, 0xfe, 0x89, 0xec, 0x9d, 0xd6, 0xb6, 0x74, 0xef, 0x78, 0x0e,
	0x50, 0x93, 0x22, 0x23, 0xab, 0x6e, 0x48, 0xdf, 0x0d, 0xc9, 0xbc, 0xb2, 0x10, 0x93, 0x57, 0x48,
	0x7c, 0x3f, 0x9e, 0x42, 0x7f, 0x45, 0x46, 0x51, 0xe3, 0x5d, 0x7b, 0xea, 0x74, 0xa9, 0xa4, 0x35,
	0x82, 0x85, 0x79, 0xd4, 0xe9, 0x7b, 0xea, 0x12, 0x71, 0x53, 0x6f, 0xdc, 0xf9, 0xb3, 0xd2, 0xd5,
	0x8f, 0x71, 0x1a, 0x8d, 0xe2, 0x32, 0xa9, 0xd6, 0xa2, 0x91, 0x8a, 0x96, 0x7d, 0xf7, 0xff, 0xaf,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x10, 0x74, 0x65, 0xd8, 0x10, 0x02, 0x00, 0x00,
}
