#!/bin/bash -e

LD_FLAGS="-w -X github.com/mikeynap/coreos-baremetal/bootcfg/version.Version=$(./git-version)"
CGO_ENABLED=0 go build -o bin/bootcfg -ldflags "$LD_FLAGS" -a github.com/mikeynap/coreos-baremetal/cmd/bootcfg

# bootcmd CLI binary
CGO_ENABLED=0 go build -o bin/bootcmd -ldflags "$LD_FLAGS" -a github.com/mikeynap/coreos-baremetal/cmd/bootcmd
