#!/bin/bash -e

# allow builds outside the standard GOPATH via symlink
export GOPATH=${PWD}/Godeps/_workspace
export GOBIN=${PWD}/bin

mkdir -p $GOPATH/src/github.com/coreos
# directory or symlink must be present
[ -d $GOPATH/src/github.com/coreos/coreos-baremetal ] || ln -s ${PWD} $GOPATH/src/github.com/coreos/coreos-baremetal

LD_FLAGS="-w -X main.version=$(./git-version)"
CGO_ENABLED=0 GOOS=linux go build -o bin/server -ldflags "$LD_FLAGS" -a -tags netgo github.com/coreos/coreos-baremetal/cmd/bootcfg
