#!/bin/bash -e

REPO=coreos/matchbox
QUAY_REPO=quay.io/coreos/matchbox
GIT_SHA=$(./git-version)

# quay.io
docker tag $REPO:$GIT_SHA $QUAY_REPO:latest
docker tag $REPO:$GIT_SHA $QUAY_REPO:$GIT_SHA
docker push $QUAY_REPO:latest
docker push $QUAY_REPO:$GIT_SHA
