#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

main() {
  cleanup
  trap cleanup EXIT

  ./scripts/devnet create
  
  pushd examples/terraform/etcd3-install
  terraform get
  terraform apply -var-file $DIR/etcd3.tfvars
  popd 

  ./scripts/libvirt create

  until etcd "node1.example.com" \
    && etcd "node2.example.com" \
    && etcd "node3.example.com"
  do
    sleep 3
    echo "Waiting for etcd cluster..."
  done

  echo "etcd3 cluster came up!"
  echo

  cleanup
}

# etcd health checks the given etcd client endpoint
etcd() {
  curl --silent --fail -m 1 http://$1:2379/health > /dev/null
}

cleanup() {
  ./scripts/libvirt destroy || true
  ./scripts/devnet destroy || true
  rkt gc --grace-period=0
  pushd examples/terraform/etcd3-install
  echo "yes" | terraform destroy || true
  rm -f *.tfstate*
  popd
}

main $@
