#!/bin/bash -e
# USAGE: ./examples/kubernetes/scripts/generate-tls

DEST=assets/tls

if [ ! -d "$DEST" ]; then
  echo "Creating directory $DEST"
  mkdir -p $DEST
fi

./examples/kubernetes/scripts/root-ca $DEST
./examples/kubernetes/scripts/kubernetes-cert $DEST admin kube-admin
./examples/kubernetes/scripts/kubernetes-cert $DEST apiserver kube-apiserver IP.1=10.3.0.1,IP.2=172.17.0.21
./examples/kubernetes/scripts/kubernetes-cert $DEST worker kube-worker IP.1=172.17.0.22

