#!/usr/bin/env bash
set -e

main() {
  cleanup
  ./scripts/devnet create etcd3
  ./scripts/libvirt create

  until etcd "172.18.0.21" && etcd "172.18.0.22" && etcd "172.18.0.23"
  do
    sleep 3
    echo "Waiting for etcd cluster..."
  done

  echo "etcd cluster came up!"
  echo

  cleanup
}

etcd() {
  curl --silent --fail -m 1 http://$1:2379/health > /dev/null
}

cleanup() {
  ./scripts/libvirt destroy || true
  ./scripts/devnet destroy || true
  rkt gc --grace-period=0
}

main $@
