#!/usr/bin/env bash
set -e

main() {
  cleanup
  ./scripts/devnet create etcd3
  ./scripts/libvirt create

  until etcd "node1.example.com" \
    && etcd "node2.example.com" \
    && etcd "node3.example.com"
  do
    sleep 3
    echo "Waiting for etcd cluster..."
  done

  echo "etcd cluster came up!"
  echo

  cleanup
}

# etcd health checks the given etcd client endpoint
etcd() {
  curl --silent --fail -m 1 http://$1:2379/health > /dev/null
}

cleanup() {
  ./scripts/libvirt destroy || true
  ./scripts/devnet destroy || true
  rkt gc --grace-period=0
}

main $@
