#!/bin/bash -e
# USAGE: ./scripts/generate-kubernetes-secrets

DEST=${1:-"assets/tls"}

if [ ! -d "$DEST" ]; then
  echo "Creating directory $DEST"
  mkdir -p $DEST
fi

./scripts/tls/root-ca $DEST
./scripts/tls/kubernetes-cert $DEST admin kube-admin
./scripts/tls/kubernetes-cert $DEST apiserver kube-apiserver IP.1=10.3.0.1,IP.2=172.17.0.21
./scripts/tls/kubernetes-cert $DEST worker kube-worker IP.1=172.17.0.22
