#!/usr/bin/env bash
# USAGE: ./scripts/get-fedora-coreos
# USAGE: ./scripts/get-fedora-coreos stream version dest arch
#
set -eou pipefail

STREAM=${1:-"stable"}
VERSION=${2:-"33.20210117.3.2"}
DEST_DIR=${3:-"$PWD/examples/assets"}
ARCH=${4:-"x86_64"}
DEST=$DEST_DIR/fedora-coreos/$ARCH
BASE_URL=https://builds.coreos.fedoraproject.org/prod/streams/$STREAM/builds/$VERSION/$ARCH

# check stream/version exist based on the header response
if ! curl -s -I $BASE_URL/fedora-coreos-$VERSION-metal.$ARCH.raw.xz | grep -q -E '^HTTP/[0-9.]+ [23][0-9][0-9]'; then
  echo "Stream, Version or Architecture not found"
  exit 1
fi

if [ ! -d "$DEST" ]; then
  echo "Creating directory $DEST"
  mkdir -p $DEST
fi

echo "Downloading Fedora CoreOS $STREAM $VERSION $ARCH images to $DEST"

# PXE kernel
echo "fedora-coreos-$VERSION-live-kernel-$ARCH"
curl -# $BASE_URL/fedora-coreos-$VERSION-live-kernel-$ARCH -o $DEST/fedora-coreos-$VERSION-live-kernel-$ARCH

# PXE initrd
echo "fedora-coreos-$VERSION-live-initramfs.$ARCH.img"
curl -# $BASE_URL/fedora-coreos-$VERSION-live-initramfs.$ARCH.img -o $DEST/fedora-coreos-$VERSION-live-initramfs.$ARCH.img

# rootfs
echo "fedora-coreos-$VERSION-live-rootfs.$ARCH.img"
curl -# $BASE_URL/fedora-coreos-$VERSION-live-rootfs.$ARCH.img -o $DEST/fedora-coreos-$VERSION-live-rootfs.$ARCH.img

# Install image
echo "fedora-coreos-$VERSION-metal.$ARCH.raw.xz"
curl -# $BASE_URL/fedora-coreos-$VERSION-metal.$ARCH.raw.xz -o $DEST/fedora-coreos-$VERSION-metal.$ARCH.raw.xz
echo "fedora-coreos-$VERSION-metal.$ARCH.raw.xz.sig"
curl -# $BASE_URL/fedora-coreos-$VERSION-metal.$ARCH.raw.xz.sig -o $DEST/fedora-coreos-$VERSION-metal.$ARCH.raw.xz.sig
