#!/usr/bin/env bash
# USAGE: ./scripts/get-ubuntu
# USAGE: ./scripts/get-coreos version dest
#
# ENV VARS:
# - OEM_ID - specify OEM image id to download, alongside the default one
set -eou pipefail

GPG=${GPG:-/usr/bin/gpg}

VERSION=${1:-"focal"}
DEST_DIR=${2:-"$PWD/examples/assets"}
DEST=$DEST_DIR/ubuntu/$VERSION
BASE_URL=http://archive.ubuntu.com/ubuntu/dists/$VERSION/main/installer-amd64/current/images/netboot/

if [ ! -d "$DEST" ]; then
  echo "Creating directory $DEST"
  mkdir -p $DEST
fi

# PXE kernel
echo "vmlinuz"
curl -# http://archive.ubuntu.com/ubuntu/dists/$VERSION/main/installer-amd64/current/legacy-images/hd-media/vmlinuz -o $DEST/vmlinuz

# PXE initrd
echo "initrd.gz"
curl -# http://archive.ubuntu.com/ubuntu/dists/$VERSION/main/installer-amd64/current/legacy-images/hd-media/initrd.gz -o $DEST/initrd.gz

# Install image
echo "boot.img.gz"
curl -# http://archive.ubuntu.com/ubuntu/dists/$VERSION/main/installer-amd64/current/legacy-images/hd-media/boot.img.gz -o $DEST/boot.img.gz