#!/usr/bin/env bash
# USAGE: ./scripts/get-ubuntu
# USAGE: ./scripts/get-coreos version dest
#
# ENV VARS:
# - OEM_ID - specify OEM image id to download, alongside the default one
set -eou pipefail

GPG=${GPG:-/usr/bin/gpg}

VERSION=${1:-"bionic"}
DEST_DIR=${2:-"$PWD/examples/assets"}
DEST=$DEST_DIR/ubuntu/$VERSION
BASE_URL=http://archive.ubuntu.com/ubuntu/dists/$VERSION/main/installer-amd64/current/images/netboot/

if [ ! -d "$DEST" ]; then
  echo "Creating directory $DEST"
  mkdir -p $DEST
fi

# PXE kernel
echo "vmlinuz"
curl -# $BASE_URL/ubuntu-installer/amd64/linux -o $DEST/linux

# PXE initrd
echo "initrd.gz"
curl -# $BASE_URL/ubuntu-installer/amd64/initrd.gz -o $DEST/initrd.gz
