#!/usr/bin/env bash
# USAGE: ./get-bootkube bin
# Get the bootkube tool
set -eu

DEST=${1:-"bin"}
VERSION="v0.3.12"

URL="https://github.com/kubernetes-incubator/bootkube/releases/download/${VERSION}/bootkube.tar.gz"

mkdir -p $DEST
curl -L -O ${URL}
tar -C $DEST --strip-components=2 -xzf bootkube.tar.gz bin/linux/bootkube
chmod +x ${DEST}/bootkube
