#!/bin/bash
set -e

REGISTRY_PORT=21504

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

images=(
	'quay.io/coreos/hyperkube:v1.3.6_coreos.0'
	'gcr.io/google_containers/kubedns-amd64:1.5'
	'gcr.io/google_containers/kube-dnsmasq-amd64:1.3'
	'gcr.io/google_containers/exechealthz-amd64:1.1'
	'gcr.io/google_containers/heapster:v1.1.0'
	'gcr.io/google_containers/addon-resizer:1.3'
	'gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.1'
	'gcr.io/google_containers/pause-amd64:3.0'
	)

for img in ${images[@]};
do
	echo "Pull $img"
	echo
	docker pull $img
    docker tag $img localhost:$REGISTRY_PORT/$(basename $img)
    echo "Push $(basename $img) into local registry"
    echo
    docker push localhost:$REGISTRY_PORT/$(basename $img)
    echo
done