// Code generated by protoc-gen-go. DO NOT EDIT.
// source: matchbox/server/serverpb/messages.proto

package serverpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	storagepb "github.com/poseidon/matchbox/matchbox/storage/storagepb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SelectGroupRequest struct {
	Labels               map[string]string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SelectGroupRequest) Reset()         { *m = SelectGroupRequest{} }
func (m *SelectGroupRequest) String() string { return proto.CompactTextString(m) }
func (*SelectGroupRequest) ProtoMessage()    {}
func (*SelectGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{0}
}

func (m *SelectGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectGroupRequest.Unmarshal(m, b)
}
func (m *SelectGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectGroupRequest.Marshal(b, m, deterministic)
}
func (m *SelectGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectGroupRequest.Merge(m, src)
}
func (m *SelectGroupRequest) XXX_Size() int {
	return xxx_messageInfo_SelectGroupRequest.Size(m)
}
func (m *SelectGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectGroupRequest proto.InternalMessageInfo

func (m *SelectGroupRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type SelectGroupResponse struct {
	Group                *storagepb.Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SelectGroupResponse) Reset()         { *m = SelectGroupResponse{} }
func (m *SelectGroupResponse) String() string { return proto.CompactTextString(m) }
func (*SelectGroupResponse) ProtoMessage()    {}
func (*SelectGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{1}
}

func (m *SelectGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectGroupResponse.Unmarshal(m, b)
}
func (m *SelectGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectGroupResponse.Marshal(b, m, deterministic)
}
func (m *SelectGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectGroupResponse.Merge(m, src)
}
func (m *SelectGroupResponse) XXX_Size() int {
	return xxx_messageInfo_SelectGroupResponse.Size(m)
}
func (m *SelectGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelectGroupResponse proto.InternalMessageInfo

func (m *SelectGroupResponse) GetGroup() *storagepb.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type SelectProfileRequest struct {
	Labels               map[string]string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SelectProfileRequest) Reset()         { *m = SelectProfileRequest{} }
func (m *SelectProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SelectProfileRequest) ProtoMessage()    {}
func (*SelectProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{2}
}

func (m *SelectProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectProfileRequest.Unmarshal(m, b)
}
func (m *SelectProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectProfileRequest.Marshal(b, m, deterministic)
}
func (m *SelectProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectProfileRequest.Merge(m, src)
}
func (m *SelectProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SelectProfileRequest.Size(m)
}
func (m *SelectProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectProfileRequest proto.InternalMessageInfo

func (m *SelectProfileRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type SelectProfileResponse struct {
	Profile              *storagepb.Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SelectProfileResponse) Reset()         { *m = SelectProfileResponse{} }
func (m *SelectProfileResponse) String() string { return proto.CompactTextString(m) }
func (*SelectProfileResponse) ProtoMessage()    {}
func (*SelectProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{3}
}

func (m *SelectProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectProfileResponse.Unmarshal(m, b)
}
func (m *SelectProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectProfileResponse.Marshal(b, m, deterministic)
}
func (m *SelectProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectProfileResponse.Merge(m, src)
}
func (m *SelectProfileResponse) XXX_Size() int {
	return xxx_messageInfo_SelectProfileResponse.Size(m)
}
func (m *SelectProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelectProfileResponse proto.InternalMessageInfo

func (m *SelectProfileResponse) GetProfile() *storagepb.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type GroupPutRequest struct {
	Group                *storagepb.Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GroupPutRequest) Reset()         { *m = GroupPutRequest{} }
func (m *GroupPutRequest) String() string { return proto.CompactTextString(m) }
func (*GroupPutRequest) ProtoMessage()    {}
func (*GroupPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{4}
}

func (m *GroupPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPutRequest.Unmarshal(m, b)
}
func (m *GroupPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPutRequest.Marshal(b, m, deterministic)
}
func (m *GroupPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPutRequest.Merge(m, src)
}
func (m *GroupPutRequest) XXX_Size() int {
	return xxx_messageInfo_GroupPutRequest.Size(m)
}
func (m *GroupPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPutRequest proto.InternalMessageInfo

func (m *GroupPutRequest) GetGroup() *storagepb.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupPutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupPutResponse) Reset()         { *m = GroupPutResponse{} }
func (m *GroupPutResponse) String() string { return proto.CompactTextString(m) }
func (*GroupPutResponse) ProtoMessage()    {}
func (*GroupPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{5}
}

func (m *GroupPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPutResponse.Unmarshal(m, b)
}
func (m *GroupPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPutResponse.Marshal(b, m, deterministic)
}
func (m *GroupPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPutResponse.Merge(m, src)
}
func (m *GroupPutResponse) XXX_Size() int {
	return xxx_messageInfo_GroupPutResponse.Size(m)
}
func (m *GroupPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPutResponse proto.InternalMessageInfo

type GroupGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupGetRequest) Reset()         { *m = GroupGetRequest{} }
func (m *GroupGetRequest) String() string { return proto.CompactTextString(m) }
func (*GroupGetRequest) ProtoMessage()    {}
func (*GroupGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{6}
}

func (m *GroupGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupGetRequest.Unmarshal(m, b)
}
func (m *GroupGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupGetRequest.Marshal(b, m, deterministic)
}
func (m *GroupGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupGetRequest.Merge(m, src)
}
func (m *GroupGetRequest) XXX_Size() int {
	return xxx_messageInfo_GroupGetRequest.Size(m)
}
func (m *GroupGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupGetRequest proto.InternalMessageInfo

func (m *GroupGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GroupGetResponse struct {
	Group                *storagepb.Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GroupGetResponse) Reset()         { *m = GroupGetResponse{} }
func (m *GroupGetResponse) String() string { return proto.CompactTextString(m) }
func (*GroupGetResponse) ProtoMessage()    {}
func (*GroupGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{7}
}

func (m *GroupGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupGetResponse.Unmarshal(m, b)
}
func (m *GroupGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupGetResponse.Marshal(b, m, deterministic)
}
func (m *GroupGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupGetResponse.Merge(m, src)
}
func (m *GroupGetResponse) XXX_Size() int {
	return xxx_messageInfo_GroupGetResponse.Size(m)
}
func (m *GroupGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupGetResponse proto.InternalMessageInfo

func (m *GroupGetResponse) GetGroup() *storagepb.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupDeleteRequest) Reset()         { *m = GroupDeleteRequest{} }
func (m *GroupDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*GroupDeleteRequest) ProtoMessage()    {}
func (*GroupDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{8}
}

func (m *GroupDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupDeleteRequest.Unmarshal(m, b)
}
func (m *GroupDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupDeleteRequest.Marshal(b, m, deterministic)
}
func (m *GroupDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupDeleteRequest.Merge(m, src)
}
func (m *GroupDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_GroupDeleteRequest.Size(m)
}
func (m *GroupDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupDeleteRequest proto.InternalMessageInfo

func (m *GroupDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GroupDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupDeleteResponse) Reset()         { *m = GroupDeleteResponse{} }
func (m *GroupDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*GroupDeleteResponse) ProtoMessage()    {}
func (*GroupDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{9}
}

func (m *GroupDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupDeleteResponse.Unmarshal(m, b)
}
func (m *GroupDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupDeleteResponse.Marshal(b, m, deterministic)
}
func (m *GroupDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupDeleteResponse.Merge(m, src)
}
func (m *GroupDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_GroupDeleteResponse.Size(m)
}
func (m *GroupDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupDeleteResponse proto.InternalMessageInfo

type GroupListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupListRequest) Reset()         { *m = GroupListRequest{} }
func (m *GroupListRequest) String() string { return proto.CompactTextString(m) }
func (*GroupListRequest) ProtoMessage()    {}
func (*GroupListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{10}
}

func (m *GroupListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupListRequest.Unmarshal(m, b)
}
func (m *GroupListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupListRequest.Marshal(b, m, deterministic)
}
func (m *GroupListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupListRequest.Merge(m, src)
}
func (m *GroupListRequest) XXX_Size() int {
	return xxx_messageInfo_GroupListRequest.Size(m)
}
func (m *GroupListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupListRequest proto.InternalMessageInfo

type GroupListResponse struct {
	Groups               []*storagepb.Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GroupListResponse) Reset()         { *m = GroupListResponse{} }
func (m *GroupListResponse) String() string { return proto.CompactTextString(m) }
func (*GroupListResponse) ProtoMessage()    {}
func (*GroupListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{11}
}

func (m *GroupListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupListResponse.Unmarshal(m, b)
}
func (m *GroupListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupListResponse.Marshal(b, m, deterministic)
}
func (m *GroupListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupListResponse.Merge(m, src)
}
func (m *GroupListResponse) XXX_Size() int {
	return xxx_messageInfo_GroupListResponse.Size(m)
}
func (m *GroupListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupListResponse proto.InternalMessageInfo

func (m *GroupListResponse) GetGroups() []*storagepb.Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type ProfilePutRequest struct {
	Profile              *storagepb.Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProfilePutRequest) Reset()         { *m = ProfilePutRequest{} }
func (m *ProfilePutRequest) String() string { return proto.CompactTextString(m) }
func (*ProfilePutRequest) ProtoMessage()    {}
func (*ProfilePutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{12}
}

func (m *ProfilePutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePutRequest.Unmarshal(m, b)
}
func (m *ProfilePutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePutRequest.Marshal(b, m, deterministic)
}
func (m *ProfilePutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePutRequest.Merge(m, src)
}
func (m *ProfilePutRequest) XXX_Size() int {
	return xxx_messageInfo_ProfilePutRequest.Size(m)
}
func (m *ProfilePutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePutRequest proto.InternalMessageInfo

func (m *ProfilePutRequest) GetProfile() *storagepb.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type ProfilePutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfilePutResponse) Reset()         { *m = ProfilePutResponse{} }
func (m *ProfilePutResponse) String() string { return proto.CompactTextString(m) }
func (*ProfilePutResponse) ProtoMessage()    {}
func (*ProfilePutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{13}
}

func (m *ProfilePutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePutResponse.Unmarshal(m, b)
}
func (m *ProfilePutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePutResponse.Marshal(b, m, deterministic)
}
func (m *ProfilePutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePutResponse.Merge(m, src)
}
func (m *ProfilePutResponse) XXX_Size() int {
	return xxx_messageInfo_ProfilePutResponse.Size(m)
}
func (m *ProfilePutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePutResponse proto.InternalMessageInfo

type ProfileGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileGetRequest) Reset()         { *m = ProfileGetRequest{} }
func (m *ProfileGetRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileGetRequest) ProtoMessage()    {}
func (*ProfileGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{14}
}

func (m *ProfileGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileGetRequest.Unmarshal(m, b)
}
func (m *ProfileGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileGetRequest.Marshal(b, m, deterministic)
}
func (m *ProfileGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileGetRequest.Merge(m, src)
}
func (m *ProfileGetRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileGetRequest.Size(m)
}
func (m *ProfileGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileGetRequest proto.InternalMessageInfo

func (m *ProfileGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProfileGetResponse struct {
	Profile              *storagepb.Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProfileGetResponse) Reset()         { *m = ProfileGetResponse{} }
func (m *ProfileGetResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileGetResponse) ProtoMessage()    {}
func (*ProfileGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{15}
}

func (m *ProfileGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileGetResponse.Unmarshal(m, b)
}
func (m *ProfileGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileGetResponse.Marshal(b, m, deterministic)
}
func (m *ProfileGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileGetResponse.Merge(m, src)
}
func (m *ProfileGetResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileGetResponse.Size(m)
}
func (m *ProfileGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileGetResponse proto.InternalMessageInfo

func (m *ProfileGetResponse) GetProfile() *storagepb.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type ProfileDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDeleteRequest) Reset()         { *m = ProfileDeleteRequest{} }
func (m *ProfileDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileDeleteRequest) ProtoMessage()    {}
func (*ProfileDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{16}
}

func (m *ProfileDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDeleteRequest.Unmarshal(m, b)
}
func (m *ProfileDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ProfileDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDeleteRequest.Merge(m, src)
}
func (m *ProfileDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileDeleteRequest.Size(m)
}
func (m *ProfileDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDeleteRequest proto.InternalMessageInfo

func (m *ProfileDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProfileDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDeleteResponse) Reset()         { *m = ProfileDeleteResponse{} }
func (m *ProfileDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileDeleteResponse) ProtoMessage()    {}
func (*ProfileDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{17}
}

func (m *ProfileDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDeleteResponse.Unmarshal(m, b)
}
func (m *ProfileDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDeleteResponse.Marshal(b, m, deterministic)
}
func (m *ProfileDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDeleteResponse.Merge(m, src)
}
func (m *ProfileDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileDeleteResponse.Size(m)
}
func (m *ProfileDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDeleteResponse proto.InternalMessageInfo

type ProfileListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileListRequest) Reset()         { *m = ProfileListRequest{} }
func (m *ProfileListRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileListRequest) ProtoMessage()    {}
func (*ProfileListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{18}
}

func (m *ProfileListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileListRequest.Unmarshal(m, b)
}
func (m *ProfileListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileListRequest.Marshal(b, m, deterministic)
}
func (m *ProfileListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileListRequest.Merge(m, src)
}
func (m *ProfileListRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileListRequest.Size(m)
}
func (m *ProfileListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileListRequest proto.InternalMessageInfo

type ProfileListResponse struct {
	Profiles             []*storagepb.Profile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProfileListResponse) Reset()         { *m = ProfileListResponse{} }
func (m *ProfileListResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileListResponse) ProtoMessage()    {}
func (*ProfileListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{19}
}

func (m *ProfileListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileListResponse.Unmarshal(m, b)
}
func (m *ProfileListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileListResponse.Marshal(b, m, deterministic)
}
func (m *ProfileListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileListResponse.Merge(m, src)
}
func (m *ProfileListResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileListResponse.Size(m)
}
func (m *ProfileListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileListResponse proto.InternalMessageInfo

func (m *ProfileListResponse) GetProfiles() []*storagepb.Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type IgnitionPutRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IgnitionPutRequest) Reset()         { *m = IgnitionPutRequest{} }
func (m *IgnitionPutRequest) String() string { return proto.CompactTextString(m) }
func (*IgnitionPutRequest) ProtoMessage()    {}
func (*IgnitionPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{20}
}

func (m *IgnitionPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IgnitionPutRequest.Unmarshal(m, b)
}
func (m *IgnitionPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IgnitionPutRequest.Marshal(b, m, deterministic)
}
func (m *IgnitionPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IgnitionPutRequest.Merge(m, src)
}
func (m *IgnitionPutRequest) XXX_Size() int {
	return xxx_messageInfo_IgnitionPutRequest.Size(m)
}
func (m *IgnitionPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IgnitionPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IgnitionPutRequest proto.InternalMessageInfo

func (m *IgnitionPutRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IgnitionPutRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type IgnitionPutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IgnitionPutResponse) Reset()         { *m = IgnitionPutResponse{} }
func (m *IgnitionPutResponse) String() string { return proto.CompactTextString(m) }
func (*IgnitionPutResponse) ProtoMessage()    {}
func (*IgnitionPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{21}
}

func (m *IgnitionPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IgnitionPutResponse.Unmarshal(m, b)
}
func (m *IgnitionPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IgnitionPutResponse.Marshal(b, m, deterministic)
}
func (m *IgnitionPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IgnitionPutResponse.Merge(m, src)
}
func (m *IgnitionPutResponse) XXX_Size() int {
	return xxx_messageInfo_IgnitionPutResponse.Size(m)
}
func (m *IgnitionPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IgnitionPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IgnitionPutResponse proto.InternalMessageInfo

type IgnitionGetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IgnitionGetRequest) Reset()         { *m = IgnitionGetRequest{} }
func (m *IgnitionGetRequest) String() string { return proto.CompactTextString(m) }
func (*IgnitionGetRequest) ProtoMessage()    {}
func (*IgnitionGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{22}
}

func (m *IgnitionGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IgnitionGetRequest.Unmarshal(m, b)
}
func (m *IgnitionGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IgnitionGetRequest.Marshal(b, m, deterministic)
}
func (m *IgnitionGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IgnitionGetRequest.Merge(m, src)
}
func (m *IgnitionGetRequest) XXX_Size() int {
	return xxx_messageInfo_IgnitionGetRequest.Size(m)
}
func (m *IgnitionGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IgnitionGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IgnitionGetRequest proto.InternalMessageInfo

func (m *IgnitionGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type IgnitionGetResponse struct {
	Config               []byte   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IgnitionGetResponse) Reset()         { *m = IgnitionGetResponse{} }
func (m *IgnitionGetResponse) String() string { return proto.CompactTextString(m) }
func (*IgnitionGetResponse) ProtoMessage()    {}
func (*IgnitionGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{23}
}

func (m *IgnitionGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IgnitionGetResponse.Unmarshal(m, b)
}
func (m *IgnitionGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IgnitionGetResponse.Marshal(b, m, deterministic)
}
func (m *IgnitionGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IgnitionGetResponse.Merge(m, src)
}
func (m *IgnitionGetResponse) XXX_Size() int {
	return xxx_messageInfo_IgnitionGetResponse.Size(m)
}
func (m *IgnitionGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IgnitionGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IgnitionGetResponse proto.InternalMessageInfo

func (m *IgnitionGetResponse) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type IgnitionDeleteRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IgnitionDeleteRequest) Reset()         { *m = IgnitionDeleteRequest{} }
func (m *IgnitionDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*IgnitionDeleteRequest) ProtoMessage()    {}
func (*IgnitionDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{24}
}

func (m *IgnitionDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IgnitionDeleteRequest.Unmarshal(m, b)
}
func (m *IgnitionDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IgnitionDeleteRequest.Marshal(b, m, deterministic)
}
func (m *IgnitionDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IgnitionDeleteRequest.Merge(m, src)
}
func (m *IgnitionDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_IgnitionDeleteRequest.Size(m)
}
func (m *IgnitionDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IgnitionDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IgnitionDeleteRequest proto.InternalMessageInfo

func (m *IgnitionDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type IgnitionDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IgnitionDeleteResponse) Reset()         { *m = IgnitionDeleteResponse{} }
func (m *IgnitionDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*IgnitionDeleteResponse) ProtoMessage()    {}
func (*IgnitionDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{25}
}

func (m *IgnitionDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IgnitionDeleteResponse.Unmarshal(m, b)
}
func (m *IgnitionDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IgnitionDeleteResponse.Marshal(b, m, deterministic)
}
func (m *IgnitionDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IgnitionDeleteResponse.Merge(m, src)
}
func (m *IgnitionDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_IgnitionDeleteResponse.Size(m)
}
func (m *IgnitionDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IgnitionDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IgnitionDeleteResponse proto.InternalMessageInfo

type GenericPutRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericPutRequest) Reset()         { *m = GenericPutRequest{} }
func (m *GenericPutRequest) String() string { return proto.CompactTextString(m) }
func (*GenericPutRequest) ProtoMessage()    {}
func (*GenericPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{26}
}

func (m *GenericPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericPutRequest.Unmarshal(m, b)
}
func (m *GenericPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericPutRequest.Marshal(b, m, deterministic)
}
func (m *GenericPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericPutRequest.Merge(m, src)
}
func (m *GenericPutRequest) XXX_Size() int {
	return xxx_messageInfo_GenericPutRequest.Size(m)
}
func (m *GenericPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenericPutRequest proto.InternalMessageInfo

func (m *GenericPutRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GenericPutRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type GenericPutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericPutResponse) Reset()         { *m = GenericPutResponse{} }
func (m *GenericPutResponse) String() string { return proto.CompactTextString(m) }
func (*GenericPutResponse) ProtoMessage()    {}
func (*GenericPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{27}
}

func (m *GenericPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericPutResponse.Unmarshal(m, b)
}
func (m *GenericPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericPutResponse.Marshal(b, m, deterministic)
}
func (m *GenericPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericPutResponse.Merge(m, src)
}
func (m *GenericPutResponse) XXX_Size() int {
	return xxx_messageInfo_GenericPutResponse.Size(m)
}
func (m *GenericPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericPutResponse proto.InternalMessageInfo

type GenericGetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericGetRequest) Reset()         { *m = GenericGetRequest{} }
func (m *GenericGetRequest) String() string { return proto.CompactTextString(m) }
func (*GenericGetRequest) ProtoMessage()    {}
func (*GenericGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{28}
}

func (m *GenericGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericGetRequest.Unmarshal(m, b)
}
func (m *GenericGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericGetRequest.Marshal(b, m, deterministic)
}
func (m *GenericGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericGetRequest.Merge(m, src)
}
func (m *GenericGetRequest) XXX_Size() int {
	return xxx_messageInfo_GenericGetRequest.Size(m)
}
func (m *GenericGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenericGetRequest proto.InternalMessageInfo

func (m *GenericGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GenericGetResponse struct {
	Config               []byte   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericGetResponse) Reset()         { *m = GenericGetResponse{} }
func (m *GenericGetResponse) String() string { return proto.CompactTextString(m) }
func (*GenericGetResponse) ProtoMessage()    {}
func (*GenericGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{29}
}

func (m *GenericGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericGetResponse.Unmarshal(m, b)
}
func (m *GenericGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericGetResponse.Marshal(b, m, deterministic)
}
func (m *GenericGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericGetResponse.Merge(m, src)
}
func (m *GenericGetResponse) XXX_Size() int {
	return xxx_messageInfo_GenericGetResponse.Size(m)
}
func (m *GenericGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericGetResponse proto.InternalMessageInfo

func (m *GenericGetResponse) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type GenericDeleteRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericDeleteRequest) Reset()         { *m = GenericDeleteRequest{} }
func (m *GenericDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*GenericDeleteRequest) ProtoMessage()    {}
func (*GenericDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{30}
}

func (m *GenericDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericDeleteRequest.Unmarshal(m, b)
}
func (m *GenericDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericDeleteRequest.Marshal(b, m, deterministic)
}
func (m *GenericDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericDeleteRequest.Merge(m, src)
}
func (m *GenericDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_GenericDeleteRequest.Size(m)
}
func (m *GenericDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenericDeleteRequest proto.InternalMessageInfo

func (m *GenericDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GenericDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericDeleteResponse) Reset()         { *m = GenericDeleteResponse{} }
func (m *GenericDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*GenericDeleteResponse) ProtoMessage()    {}
func (*GenericDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae62049dfcf497b5, []int{31}
}

func (m *GenericDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericDeleteResponse.Unmarshal(m, b)
}
func (m *GenericDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericDeleteResponse.Marshal(b, m, deterministic)
}
func (m *GenericDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericDeleteResponse.Merge(m, src)
}
func (m *GenericDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_GenericDeleteResponse.Size(m)
}
func (m *GenericDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericDeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SelectGroupRequest)(nil), "serverpb.SelectGroupRequest")
	proto.RegisterMapType((map[string]string)(nil), "serverpb.SelectGroupRequest.LabelsEntry")
	proto.RegisterType((*SelectGroupResponse)(nil), "serverpb.SelectGroupResponse")
	proto.RegisterType((*SelectProfileRequest)(nil), "serverpb.SelectProfileRequest")
	proto.RegisterMapType((map[string]string)(nil), "serverpb.SelectProfileRequest.LabelsEntry")
	proto.RegisterType((*SelectProfileResponse)(nil), "serverpb.SelectProfileResponse")
	proto.RegisterType((*GroupPutRequest)(nil), "serverpb.GroupPutRequest")
	proto.RegisterType((*GroupPutResponse)(nil), "serverpb.GroupPutResponse")
	proto.RegisterType((*GroupGetRequest)(nil), "serverpb.GroupGetRequest")
	proto.RegisterType((*GroupGetResponse)(nil), "serverpb.GroupGetResponse")
	proto.RegisterType((*GroupDeleteRequest)(nil), "serverpb.GroupDeleteRequest")
	proto.RegisterType((*GroupDeleteResponse)(nil), "serverpb.GroupDeleteResponse")
	proto.RegisterType((*GroupListRequest)(nil), "serverpb.GroupListRequest")
	proto.RegisterType((*GroupListResponse)(nil), "serverpb.GroupListResponse")
	proto.RegisterType((*ProfilePutRequest)(nil), "serverpb.ProfilePutRequest")
	proto.RegisterType((*ProfilePutResponse)(nil), "serverpb.ProfilePutResponse")
	proto.RegisterType((*ProfileGetRequest)(nil), "serverpb.ProfileGetRequest")
	proto.RegisterType((*ProfileGetResponse)(nil), "serverpb.ProfileGetResponse")
	proto.RegisterType((*ProfileDeleteRequest)(nil), "serverpb.ProfileDeleteRequest")
	proto.RegisterType((*ProfileDeleteResponse)(nil), "serverpb.ProfileDeleteResponse")
	proto.RegisterType((*ProfileListRequest)(nil), "serverpb.ProfileListRequest")
	proto.RegisterType((*ProfileListResponse)(nil), "serverpb.ProfileListResponse")
	proto.RegisterType((*IgnitionPutRequest)(nil), "serverpb.IgnitionPutRequest")
	proto.RegisterType((*IgnitionPutResponse)(nil), "serverpb.IgnitionPutResponse")
	proto.RegisterType((*IgnitionGetRequest)(nil), "serverpb.IgnitionGetRequest")
	proto.RegisterType((*IgnitionGetResponse)(nil), "serverpb.IgnitionGetResponse")
	proto.RegisterType((*IgnitionDeleteRequest)(nil), "serverpb.IgnitionDeleteRequest")
	proto.RegisterType((*IgnitionDeleteResponse)(nil), "serverpb.IgnitionDeleteResponse")
	proto.RegisterType((*GenericPutRequest)(nil), "serverpb.GenericPutRequest")
	proto.RegisterType((*GenericPutResponse)(nil), "serverpb.GenericPutResponse")
	proto.RegisterType((*GenericGetRequest)(nil), "serverpb.GenericGetRequest")
	proto.RegisterType((*GenericGetResponse)(nil), "serverpb.GenericGetResponse")
	proto.RegisterType((*GenericDeleteRequest)(nil), "serverpb.GenericDeleteRequest")
	proto.RegisterType((*GenericDeleteResponse)(nil), "serverpb.GenericDeleteResponse")
}

func init() {
	proto.RegisterFile("matchbox/server/serverpb/messages.proto", fileDescriptor_ae62049dfcf497b5)
}

var fileDescriptor_ae62049dfcf497b5 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x53, 0x1a, 0xca, 0x04, 0x41, 0xb2, 0x71, 0xda, 0xa8, 0xa7, 0x62, 0x50, 0x6b, 0x95,
	0xe2, 0x48, 0x45, 0x08, 0x5a, 0xa9, 0xa2, 0x44, 0x44, 0x11, 0x52, 0x0f, 0x55, 0xb8, 0x71, 0xb3,
	0x93, 0xa9, 0x6b, 0xe1, 0x78, 0x8d, 0xbd, 0xae, 0xe8, 0xcf, 0xe0, 0xc0, 0xff, 0x45, 0x59, 0xcf,
	0xda, 0x6b, 0x37, 0xfd, 0x08, 0xea, 0xc9, 0xbb, 0xb3, 0x6f, 0xde, 0xbc, 0xf7, 0x36, 0xd1, 0xc2,
	0xde, 0xdc, 0x15, 0xd3, 0x4b, 0x8f, 0xff, 0x1e, 0xa4, 0x98, 0x5c, 0x61, 0x42, 0x9f, 0xd8, 0x1b,
	0xcc, 0x31, 0x4d, 0x5d, 0x1f, 0x53, 0x27, 0x4e, 0xb8, 0xe0, 0x6c, 0x43, 0x1d, 0x6c, 0xdb, 0x65,
	0x8b, 0xe0, 0x89, 0xeb, 0xa3, 0xfa, 0xc6, 0x9e, 0x5a, 0xe5, 0x3d, 0xd6, 0x1f, 0x03, 0xd8, 0x77,
	0x0c, 0x71, 0x2a, 0xc6, 0x09, 0xcf, 0xe2, 0x09, 0xfe, 0xca, 0x30, 0x15, 0xec, 0x14, 0x9a, 0xa1,
	0xeb, 0x61, 0x98, 0xf6, 0x8d, 0x9d, 0x35, 0xbb, 0x75, 0x68, 0x3b, 0x8a, 0xdb, 0xb9, 0x89, 0x76,
	0xce, 0x24, 0x74, 0x14, 0x89, 0xe4, 0x7a, 0x42, 0x7d, 0xdb, 0x47, 0xd0, 0xd2, 0xca, 0xac, 0x0d,
	0x6b, 0x3f, 0xf1, 0xba, 0x6f, 0xec, 0x18, 0xf6, 0xb3, 0xc9, 0x62, 0xc9, 0x4c, 0x58, 0xbf, 0x72,
	0xc3, 0x0c, 0xfb, 0x0d, 0x59, 0xcb, 0x37, 0xc7, 0x8d, 0x4f, 0x86, 0x75, 0x02, 0xdd, 0xca, 0x90,
	0x34, 0xe6, 0x51, 0x8a, 0x6c, 0x17, 0xd6, 0xfd, 0x45, 0x41, 0x92, 0xb4, 0x0e, 0xdb, 0x4e, 0xe1,
	0xc9, 0xc9, 0x81, 0xf9, 0xb1, 0xf5, 0xd7, 0x00, 0x33, 0xef, 0x3f, 0x4f, 0xf8, 0x45, 0x10, 0xa2,
	0x32, 0x35, 0xac, 0x99, 0xda, 0xaf, 0x9b, 0xaa, 0xe2, 0x1f, 0xdb, 0xd6, 0x08, 0x7a, 0xb5, 0x31,
	0x64, 0xec, 0x00, 0x9e, 0xc6, 0x79, 0x89, 0xac, 0x31, 0xcd, 0x9a, 0x02, 0x2b, 0x88, 0x75, 0x04,
	0x2f, 0xa5, 0xdd, 0xf3, 0x4c, 0x28, 0x63, 0x0f, 0x4d, 0x86, 0x41, 0xbb, 0x6c, 0xcd, 0x87, 0x5b,
	0xaf, 0x88, 0x6e, 0x8c, 0x05, 0xdd, 0x0b, 0x68, 0x04, 0x33, 0xf2, 0xd4, 0x08, 0x66, 0xd6, 0x31,
	0xb5, 0x49, 0xc8, 0x8a, 0x97, 0xf1, 0x06, 0x98, 0xdc, 0x7f, 0xc5, 0x10, 0x05, 0xde, 0x36, 0xa1,
	0x07, 0xdd, 0x0a, 0x8a, 0xb4, 0x29, 0xbd, 0x67, 0x41, 0xaa, 0xc4, 0x59, 0x27, 0xd0, 0xd1, 0x6a,
	0xa4, 0xc6, 0x86, 0xa6, 0x1c, 0xa7, 0x6e, 0xf6, 0xa6, 0x1c, 0x3a, 0xb7, 0xbe, 0x40, 0x87, 0x12,
	0xd5, 0xf2, 0x5b, 0xed, 0x02, 0x4c, 0x60, 0x3a, 0x05, 0x69, 0x7d, 0x5d, 0x10, 0xdf, 0x91, 0xe4,
	0xb0, 0x68, 0xd5, 0xb3, 0x5c, 0x6d, 0xfc, 0x2e, 0x98, 0x54, 0xbb, 0x3b, 0xd3, 0x2d, 0xe8, 0xd5,
	0x70, 0xa4, 0xb4, 0xd4, 0xaf, 0xe7, 0x3a, 0x82, 0x6e, 0xa5, 0x4a, 0xda, 0x1c, 0xd8, 0xa0, 0xc1,
	0x2a, 0xdb, 0x65, 0xe2, 0x0a, 0x8c, 0x75, 0x0a, 0xec, 0x9b, 0x1f, 0x05, 0x22, 0xe0, 0x91, 0x16,
	0x30, 0x83, 0x27, 0x91, 0x3b, 0x47, 0x52, 0x27, 0xd7, 0x6c, 0x13, 0x9a, 0x53, 0x1e, 0x5d, 0x04,
	0xbe, 0xfc, 0xa7, 0x3c, 0x9f, 0xd0, 0x6e, 0xf1, 0x5b, 0xa8, 0x30, 0x90, 0x6a, 0xbb, 0x24, 0xd6,
	0x02, 0x5e, 0x42, 0x6c, 0xbd, 0x2b, 0x09, 0xf4, 0x94, 0xcb, 0x79, 0x46, 0x65, 0xde, 0x5b, 0xe8,
	0x29, 0x78, 0x35, 0xd0, 0x65, 0xdc, 0x7d, 0xd8, 0xac, 0x83, 0x49, 0xdf, 0x67, 0xe8, 0x8c, 0x31,
	0xc2, 0x24, 0x98, 0xfe, 0xa7, 0x6f, 0x13, 0x98, 0x4e, 0x40, 0xb4, 0x7b, 0x05, 0xed, 0x3d, 0xae,
	0x0f, 0x8a, 0xf6, 0x87, 0x98, 0xde, 0x07, 0x93, 0xd0, 0xf7, 0x7b, 0xde, 0x82, 0x5e, 0x0d, 0x9b,
	0x93, 0x0f, 0x3f, 0xfe, 0xf8, 0xe0, 0x07, 0xe2, 0x32, 0xf3, 0x9c, 0x29, 0x9f, 0x0f, 0x62, 0x9e,
	0x62, 0x30, 0xe3, 0xd1, 0xa0, 0x78, 0x7b, 0x6e, 0x7b, 0xb7, 0xbc, 0xa6, 0x7c, 0x7b, 0xde, 0xff,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x45, 0xe3, 0xd0, 0xda, 0x06, 0x00, 0x00,
}
