name: wait-for-status-checks
on:
  workflow_call:
jobs:
  status-checks:
    runs-on: ubuntu-slim
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@e7e24423722c5b8e97a6dd5848827d2a412f812d # v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # wait-for-status-checks ignores it's own check name, but it does
          # not know the full name when used inside a reusable workflow
          ignore: "enforce / status-checks"
