name: wait-for-status-checks
on:
  workflow_call:
jobs:
  status-checks:
    runs-on: [self-hosted, Linux, X64]
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@6988432d64ad3f9c2608db4ca16fded1b7d36ead # v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # wait-for-status-checks ignores it's own check name, but it does
          # not know the full name when used inside a reusable workflow
          ignore: "enforce / status-checks"
