name: wait-for-status-checks
on:
  workflow_call:
jobs:
  status-checks:
    runs-on: [self-hosted, Linux, X64]
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707 # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # wait-for-status-checks ignores it's own check name, but it does
          # not know the full name when used inside a reusable workflow
          ignore: "enforce / status-checks"
